#!/bin/bash

reset

OLDPWD=`pwd`
cd $POSBUILDROOT

echo Starting newlib compilation for target $1

TCPREFIX="$POSBUILDROOT/toolchains"
PREFIX="/usr"
TARGET=$1
PATH="$TCPREFIX/bin:$PATH"
TARG_CFGNEWLIB="$POSBUILDROOT/etc/targets/$TARGET/newlib_configure"
PKG_NEWLIB=`cat etc/pkg_newlib`
BDIR_NEWLIB="build/newlib-$TARGET"
SDIR_NEWLIB="$POSBUILDROOT/src3m/$PKG_NEWLIB"

echo newlib package: $PKG_NEWLIB

if [ ! -d "$SDIR_NEWLIB" ]; then
        echo "No such package: $PKG_NEWLIB" >&2
        exit
fi

if [ ! -d "$POSBUILDROOT/etc/targets/$TARGET" ]; then
        echo "No such target: $TARGET" >&2
        exit
fi

source "$TARG_CFGNEWLIB"

if [ ! -d "$BDIR_NEWLIB" ]; then
	echo "Creating build directory for newlib: " $BDIR_NEWLIB
	mkdir "$BDIR_NEWLIB"
fi

cd "$BDIR_NEWLIB"
if [ -z "$2" ]; then
	echo "Configuring newlib..."
	{
		$SDIR_NEWLIB/configure --target=$TARGET --prefix="$PREFIX" \
				$NEWLIB_CFG
	} || {
		echo "Failed to configure newlib!" >&2
		exit
	}
fi

echo "Building newlib..."
{
	make tooldir=$PREFIX DESTDIR="$POSBUILDROOT/sysroot/$TARGET"
} || {
	echo "Failed to build newlib!" >&2
	exit
}

echo "Installing newlib..."
{
	make tooldir=$PREFIX install DESTDIR="$POSBUILDROOT/sysroot/$TARGET" &&
	install "$TARGET/newlib/libc/sys/posnk/crti.o" "$POSBUILDROOT/sysroot/$TARGET/usr/lib/crti.o" &&
	install "$TARGET/newlib/libc/sys/posnk/crtn.o" "$POSBUILDROOT/sysroot/$TARGET/usr/lib/crtn.o"	
	
} || {
	echo "Failed to install newlib!" >&2
	exit
}

echo "Done"

cd $OLDPWD
