#!/bin/bash

OLDPWD=`pwd`
cd $POSBUILDROOT

echo Starting $1 compilation for target $2

TCPREFIX="$POSBUILDROOT/toolchains"
PRG=$1
TARGET=$2
PATH="$TCPREFIX/bin:$PATH"
BDIR_PRG="$POSBUILDROOT/build/$PRG-$TARGET"
SDIR_PRG="$POSBUILDROOT/src/$PRG"

export PKG_CONFIG_LIBDIR=$POSBUILDROOT/sysroot/$TARGET/usr/lib/pkgconfig
export PKG_CONFIG_SYSROOT_DIR=$POSBUILDROOT/sysroot/$TARGET
export PKG_CONFIG_PATH=$PKG_CONFIG_LIBDIR

if [ ! -d "$SDIR_PRG" ]; then
        echo "No such program: $PRG" >&2
        exit 1
fi

if [ ! -d "$POSBUILDROOT/etc/targets/$TARGET" ]; then
        echo "No such target: $TARGET" >&2
        exit 1
fi

if [ ! -d "$BDIR_PRG" ]; then
	echo "Creating build directory for $PRG: " $BDIR_PRG
	mkdir "$BDIR_PRG"
fi

cd "$SDIR_PRG"

echo "Building $PRG..."
{
	make TARGET=$TARGET BUILDDIR="$BDIR_PRG/" DESTDIR="$POSBUILDROOT/sysroot/$TARGET"
} || {
	echo "Failed to build $PRG!" >&2
	exit 1
}

echo "Installing $1..."
{
	make TARGET=$TARGET BUILDDIR="$BDIR_PRG/" DESTDIR="$POSBUILDROOT/sysroot/$TARGET" install
	
} || {
	echo "Failed to install $PRG!" >&2
	exit 1
}

echo "Done"

cd $OLDPWD
