#!/bin/bash
# Installs the build environment on a new system
# Usage: installenv <install dir>

INSTALLDIR=$1
BUILDENVGIT="https://github.com/posnk/buildenv.git"
PKGSGIT="https://github.com/posnk/pkgs.git"
PATCHESGIT="https://github.com/posnk/patches.git"

if [ -z "$INSTALLDIR" ]; then
	echo "Usage: installenv <install dir>" >&2
	exit
fi

if [ -d "$INSTALLDIR" ]; then
	echo "Error: installation directory already exists!" >&2
	exit
fi

echo "Installing build environment in: " $INSTALLDIR

mkdir "$INSTALLDIR" || {
	echo "Could not create install directory!" >&2
	exit
}

cd "$INSTALLDIR"

echo "Creating directory structure..."
{
	mkdir log &&
	mkdir build &&
	mkdir src &&
	mkdir src3m &&
	mkdir src3p &&
	mkdir sysroot &&
	mkdir tmp &&
	mkdir toolchains  &&
	mkdir var &&
	mkdir var/pkgs &&
	mkdir var/targets 
} || {
	echo "Could not create directory structure!" >&2
	exit
}

echo "Cloning build environment from git..."
{
	cd src &&
	git clone "$BUILDENVGIT" &&
	cd ..
} || {
	echo "Could not clone build environment!" >&2
	exit
}

echo "Cloning patch collection from git..."
{
	cd src &&
	git clone "$PATCHESGIT" &&
	cd ..
} || {
	echo "Could not clone patches!" >&2
	exit
}

echo "Cloning package database from git..."
{
	cd src &&
	git clone "$PKGSGIT" &&
	cd ..
} || {
	echo "Could not clone package database!" >&2
	exit
}

echo "Installing build environment binaries and configuration..."
{
	ln -s src/buildenv/scripts bin &&
	ln -s src/buildenv/config etc &&
	ln -s src/patches patch &&
	ln -s src/pkgs pkgs
} || {
	echo "Could not install build environment!"
	exit
}

echo "Build environment has been installed in $INSTALLDIR"
echo "From \"$INSTALLDIR\" invoke ./bin/startenv to launch the build environment"
echo "Run pkg_mktarget <target triple> in order to prepare a target environment"
echo "For i386, the correct target is: i386-pc-posnk"
