#!/bin/bash
# posnk package manager, target creation module
# written by Peter Bosch <peterbosc@gmail.com>

PKGMGR_TARGET="$1"
PKGMGR_TARGETTOKEN="$POSBUILDROOT/var/targets/$PKGMGR_TARGET"
PKGMGR_DEPFILE="/tmp/postoolchain.dep"

if [ -z "$PKGMGR_TARGET" ]; then
	echo "Usage: pkg_mktarget <target>"
	exit 255
fi

if [ -f "$PKGMGR_TARGETTOKEN" -a "$PKGMGR_FORCETGT" != "yes" ]; then

	echo "Target is already installed"
	echo "In order to force a reinstall of the target, run:"
	echo "PKGMGR_FORCETGT=yes pkg_mktarget $1"
	exit 255

fi

echo "Downloading toolchain sources..."

if [ -f "$PKGMGR_DEPFILE" ]; then
	rm "$PKGMGR_DEPFILE"
fi

pkg_gendep meta/hosttools "$PKGMGR_DEPFILE" || {
	echo "Error resolving dependencies!"
	exit 255
}

pkg_askdep "downloaded" "$PKGMGR_DEPFILE" || {
	exit 255
}

pkg_dodep "$PKGMGR_DEPFILE" "pkg_get" || {
	echo "Failed to download all dependencies!"
	exit 255
}

rm "$PKGMGR_DEPFILE" || {
	echo "Warning: failed to remove temporary file: $PKGMGR_TARGETTOKEN"
}

mkroot "$PKGMGR_TARGET" || {
	exit 255
}

mktoolchain "$PKGMGR_TARGET" || {
	exit 255
}

pkg_mkinst lib/newlib-2.1.0

touch "$PKGMGR_TARGETTOKEN"

echo "Successfully installed target!"
echo "To select this target, enter:"
echo "export PKGENV_TARGET=$PKGMGR_TARGET"
echo "To set it as the default, enter:"
echo "echo $PKGMGR_TARGET > $POSBUILDROOT/etc/deftarget"

exit 0

