#!/bin/bash
# posnk package manager, package download module
# written by Peter Bosch <peterbosc@gmail.com>

. pkg_load

PKGMGR_DLTOKEN="$POSBUILDROOT/var/pkgs/$PKGINFO_NAME""_dl"

if [ "$PKGINFO_FETCHTYPE" = "meta" ]; then

	exit 0

fi

if [  -f "$PKGMGR_DLTOKEN" ]; then
	PKGMGR_DLVERSION=`cat $PKGMGR_DLTOKEN`
	if [ "$PKGMGR_DLVERSION" != "$PKGINFO_VERSION" ]; then

		echo "Upgrading $PKGMGR_PKG from $PKGMGR_DLVERSION \
to $PKGINFO_VERSION"

	elif [ "$PKGMGR_FORCEDL" != "yes" ]; then
		echo "Package $PKGMGR_PKG already download!"
		echo "Run PKGMGR_FORCEDL=yes pkg_get $1 to force download"
		exit 0
	fi
fi

if [ "$PKGMGR_VERBOSE" = "yes" ]; then

	echo "Downloading package: $PKGINFO_NAME"
	echo "Download type: $PKGINFO_FETCHTYPE"

fi

if [ "$PKGINFO_FETCHTYPE" = "dist" ]; then

	if [ -d "$POSBUILDROOT/src3p/$PKGINFO_NAME" ]; then

		echo "Upstream source already downloaded"

	else

		if [ "$PKGMGR_VERBOSE" = "yes" ]; then
			echo "Doing dist fetch"
			echo "Extraction options: $PKGINFO_FETCHOPTS"
			echo "Download URL: $PKGINFO_FETCHURL"
		fi

		echo "Downloading package $PKGINFO_NAME ..."
		fetchpkg "$PKGINFO_FETCHOPTS" "$PKGINFO_FETCHURL" || {
			echo "Could not fetch package!"
			exit 255
		}

	fi


elif [ "$PKGINFO_FETCHTYPE" = "git" ]; then

	echo "Cloning package $PKGINFO_PKG ..."

	cd "$POSBUILDROOT/src"

	git clone "$PKGINFO_GITURL"

elif [ "$PKGINFO_FETCHTYPE" = "git3p" ]; then

	echo "Cloning package $PKGINFO_PKG ..."

	cd "$POSBUILDROOT/src3p"

	git clone "$PKGINFO_GITURL"

else

	echo "Invalid package fetch type!"
	exit 255

fi
if [ "$PKGINFO_PATCHTYPE" = "old" ]; then

	echo "Patching upstream package..."

	if [ -d "$POSBUILDROOT/src3m/$PKGINFO_NAME" ]; then
		echo "Removing old patched sources..."
		rm -r "$POSBUILDROOT/src3m/$PKGINFO_NAME" || {
			echo "Could not remove old patched sources for package $PKGMGR_PKG"
			exit 255
		}
	fi

	patchpkg "$PKGINFO_NAME" || {
		echo "Could not patch package!"
		exit 255
	}

elif [ "$PKGINFO_PATCHTYPE" = "pkg" ]; then

	echo "Patching upstream package..."

	if [ ! -d "$POSBUILDROOT/src3p/$PKGINFO_NAME" ]; then
		echo "Package $PKGMGR_PKG specified an incorrect PKGINFO_NAME!"
		exit 255
	fi

	if [ ! -f "$PKGMGR_PKGDIR/posnk.patch" ]; then
		echo "Missing patchfile for package $PKGMGR_PKG !"
		exit 255
	fi

	if [ -d "$POSBUILDROOT/src3m/$PKGINFO_NAME" ]; then
		echo "Removing old patched sources..."
		rm -r "$POSBUILDROOT/src3m/$PKGINFO_NAME" || {
			echo "Could not remove old patched sources for package $PKGMGR_PKG"
			exit 255
		}
	fi

	cd "$POSBUILDROOT/src3m"

	cp -r "../src3p/$PKGINFO_NAME" "./$PKGINFO_NAME"
	patch -p0 < "$PKGMGR_PKGDIR/posnk.patch" > /dev/null

elif [ "$PKGINFO_PATCHTYPE" = "upstream" ]; then

	editpkg "$PKGINFO_NAME"	|| {
		echo "Could not instantiate local clone..."
		exit 255
	}

fi

echo "$PKGINFO_VERSION" > $PKGMGR_DLTOKEN

echo Package downloaded!

exit 0
